-- Номер пользователя: 1, 2, 3… по порядку регистрации.
--
-- Длинный uuid вслух не продиктуешь, а номер — легко: «я сто двенадцатый».
-- Живёт отдельной таблицей, а не в profiles: профиль человек правит сам
-- (тема, валюта), а номер менять не должен никто. Поэтому здесь только
-- чтение своей строки, а выдаёт номера триггер на регистрацию.
create table public.user_numbers (
  user_id uuid primary key references auth.users (id) on delete cascade,
  number bigint generated by default as identity unique
);

alter table public.user_numbers enable row level security;
revoke all on public.user_numbers from anon, authenticated;
grant select on public.user_numbers to authenticated;

create policy "own number" on public.user_numbers
  for select to authenticated
  using (user_id = (select auth.uid()));

-- Уже зарегистрированным — по порядку регистрации, дальше счётчик
-- продолжает с последнего.
insert into public.user_numbers (user_id, number)
select id, row_number() over (order by created_at, id)
from auth.users;

select setval(
  pg_get_serial_sequence('public.user_numbers', 'number'),
  greatest((select max(number) from public.user_numbers), 1),
  (select count(*) > 0 from public.user_numbers)
);

create or replace function public.assign_user_number()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_numbers (user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

revoke execute on function public.assign_user_number() from public, anon, authenticated;

create trigger on_auth_user_numbered
  after insert on auth.users
  for each row execute function public.assign_user_number();

-- Сводка для админки.
--
-- Сумм, названий операций и текстов задач здесь нет намеренно: на экране
-- входа людям обещано, что их данные видят только они. Владельцу хватает
-- счётчиков, чтобы понять, кто и насколько пользуется приложениями.
create or replace function public.admin_overview()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  month_ago timestamptz := now() - interval '30 days';
  week_ago  timestamptz := now() - interval '7 days';
begin
  if not exists (select 1 from public.admins a where a.user_id = auth.uid()) then
    raise exception 'Нет доступа' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'generated_at', now(),

    'users', coalesce((
      select jsonb_agg(row_to_json(u) order by u.created_at desc)
      from (
        select
          au.id,
          un.number,
          au.email,
          p.display_name,
          au.created_at,
          -- «Был последний раз» — по самому свежему следу: вход, обновление
          -- сессии или запись. Одного last_sign_in_at мало: с долгой сессией
          -- человек неделями не входит заново, хотя пользуется каждый день.
          greatest(
            au.last_sign_in_at,
            pr.seen_at,
            (select max(s.refreshed_at) from auth.sessions s where s.user_id = au.id),
            (select max(t.created_at) from public.transactions t where t.user_id = au.id),
            (select max(k.created_at) from public.tasks k where k.user_id = au.id)
          ) as last_seen,
          pr.seen_at as online_at,
          coalesce((select jsonb_agg(distinct i.provider) from auth.identities i where i.user_id = au.id), '[]'::jsonb) as providers,
          (select count(*) from public.wallets w where w.user_id = au.id and not w.archived) as wallets,
          (select count(*) from public.transactions t where t.user_id = au.id) as transactions,
          (select count(*) from public.tasks k where k.user_id = au.id and not k.done) as tasks_open,
          (select count(*) from public.tasks k where k.user_id = au.id and k.done) as tasks_done,
          exists (select 1 from public.ai_keys ak where ak.user_id = au.id) as has_ai_key,
          coalesce((select sum(g.calls) from public.ai_usage g where g.user_id = au.id), 0) as ai_calls
        from auth.users au
        left join public.profiles p on p.id = au.id
        left join public.presence pr on pr.user_id = au.id
        left join public.user_numbers un on un.user_id = au.id
        where au.deleted_at is null
      ) u
    ), '[]'::jsonb),

    'totals', jsonb_build_object(
      -- «Онлайн» — отметился за последние две минуты: открытое приложение
      -- отмечается раз в минуту, свёрнутое — молчит.
      'online',      (select count(*) from public.presence where seen_at > now() - interval '2 minutes'),
      'users',       (select count(*) from auth.users where deleted_at is null),
      'new_7d',      (select count(*) from auth.users where deleted_at is null and created_at > week_ago),
      'new_30d',     (select count(*) from auth.users where deleted_at is null and created_at > month_ago),
      -- Активные по правилам Supabase: вошёл или обновил сессию за 30 дней.
      -- Именно их считает лимит «Monthly Active Users».
      'active_7d',   (select count(distinct x.id) from (
                        select id from auth.users where last_sign_in_at > week_ago
                        union select user_id from auth.sessions where refreshed_at > week_ago) x),
      'active_30d',  (select count(distinct x.id) from (
                        select id from auth.users where last_sign_in_at > month_ago
                        union select user_id from auth.sessions where refreshed_at > month_ago) x),
      'money_users', (select count(distinct user_id) from public.transactions),
      'tasks_users', (select count(distinct user_id) from public.tasks),
      'transactions',(select count(*) from public.transactions),
      'tasks',       (select count(*) from public.tasks)
    ),

    'database', jsonb_build_object(
      'size_bytes',  pg_catalog.pg_database_size(current_database()),
      'tables', coalesce((
        select jsonb_agg(jsonb_build_object('name', t.relname, 'bytes', t.bytes, 'rows', t.rows) order by t.bytes desc)
        from (
          -- Строки — из счётчика живых строк: reltuples, взятый было сначала,
          -- у ни разу не проанализированной таблицы честно отвечает «−1».
          select c.relname, pg_catalog.pg_total_relation_size(c.oid) as bytes,
                 coalesce(st.n_live_tup, 0) as rows
          from pg_catalog.pg_class c
          join pg_catalog.pg_namespace n on n.oid = c.relnamespace
          left join pg_catalog.pg_stat_user_tables st on st.relid = c.oid
          where n.nspname = 'public' and c.relkind = 'r'
        ) t
      ), '[]'::jsonb)
    ),

    'storage', jsonb_build_object(
      'size_bytes', coalesce((select sum((o.metadata->>'size')::bigint) from storage.objects o), 0),
      'files',      (select count(*) from storage.objects)
    )
  );
end;
$$;

